# -*- coding: utf-8 -*-
"""Assignment No. 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n57x9zt7xNdvHS7OVWknRndckoA1fBcw

# **1. Find out all the types of error that we have encountered in our lecture and why? Also include the examples.**

*i. For case sensetivity:*
"""

TEN = 10
ten = 20
print(Ten)

"""*ii. We should not use reserved words as variable names*"""

print("Hi there")

print = "Hi there" # as a variable
type(print)

print("Hi there")

# delete the variable print
del print

"""*iii. Whenever we will take user input variable, we should mention the datatype. Because by default it takes as string literal. Thy for next use, the input can create an issue, like through an error or may lead to an unexpected output.*"""

# calcualte the age of the user

name = input("Name: ") # always gives you string values
place = input("place: ")
year_of_birth = input("year_of_birth: ")

age = 2022 - year_of_birth

print(f"""
My name is: {name}
I live at: {place}
{name} is of age: {age}
""")

"""*iv. If we mentioned the datatype of input variable, then we need to remember, while putting the value, we need to put exact mentioned datatype's value.*"""

A = float(input("Enter value of A: "))
B = int(input("Enter value of B: ")) # 10.2 is float but converting to int

print(f"Sum of A and B is: {A+B}")

"""*v. We can't change an empty string to any datatype*"""

# empty string to int
A = ""
print(f"data type before: {type(A)}, value of A: {A}")
A = int(A)
print(f"data type after: {type(A)}, value of A: {A}")

"""# **2. Take input A and B and print their sum, mul, div, square of the nos.**"""

# taking the user inputs
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))

# mathematical equations
sum = a + b
mul = a * b
div = a / b
square = a ** 2

print()

# printing the results
print(f"The 'sum' of {a} & {b} is: {sum}")
print(f"The 'mul' of {a} & {b} is: {mul}")
print(f"The 'div' of {a} & {b} is: {div}")
print(f"The 'square' of {a} & {b} is: {square}")

"""# **3. How many reserve keywords are there in python and why we should not use them as a variable name.**

* There are only 33 reserve keywords in python.
* We shouldn't use those as variable name because if I will use those words as variable, then those might revert in the data type of the variable, and for future use of those variable as keywords, will through an error.

# **4. Create email ids with the user inputs. in the following format - lastname.firstname@gmail.com**
"""

# taking the user inputs
first_name = input("Enter the first name: ")
last_name = input("Enter the last name: ")

# creating the email id
print(f"The user email id is: {last_name}.{first_name}@gmail.com")

"""# 5. Try to print the following lines -
 * **Hi I'm Sunny**
 * **My address is 22\3**
 * **I earn 20$ daily.**  
"""

# taking the user inputs
statement_1 = "Hi I'm Sunny"
statement_2 = "My address is 22\\3"
statement_3 = "I earn 20$ daily."

# printing the statements
print(f"The 1st statement is: {statement_1}")
print(f"The 2nd statement is: {statement_2}")
print(f"The 3rd statement is: {statement_3}")

"""# **6. Take user input (name, address, date of birth etc) to fill a form for your college and print their email IDs**"""

# taking the user inputs
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

house_no = input("Enter your house_no: ")
vill_or_city = input("Enter your Village/City name: ")
po = input("Enter your Post Office: ")
ps = input("Enter your Police Station: ")
pin = input("Enter your Postal Code: ")
dist = input("Enter your District: ")
state = input("Enter your State: ")

dob = input("Enter your date of birth: ")

# printing the outputs
print(f"\nYour full name: {first_name} {last_name}")

print()

print(f"""Your full address:- 
house_no: {house_no},
Village/City name: {vill_or_city},
Post Office: {po},
Police Station: {ps},
Postal Code: {pin},
District: {dist},
State: {state}""")

print()

print(f"Your D.O.B. is: {dob}")

print()


# creating the email id
print(f"The user email id is: {(last_name.lower())}.{(first_name.lower())}@gmail.com")

"""7. Convert the following -
 * "22.4" into integer
 * "22" into complex no.
"""

# float to integer
x = 22.4
print(f"The data type of given number is: {type(x)}, value of x: {x}")
x = int(x)
print(f"After converting '22.4' into integer: {x}")

print()

# integer to float
y = 22
print(f"The data type of given number is: {type(y)}, value of x: {y}")
y = float(y)
print(f"After converting '22' into float: {y}")